version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  redis:
    image: redis:latest

  airflow-webserver:
    image: apache/airflow:2.9.1-python3.9
    depends_on:
      - postgres
      - redis
    env_file:
      - ../.env
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "Etx684jFCwof8lADNZ8quOGEbG_eo6kh7HgFnKqbs8k"
    volumes:
      - ./dags:/opt/airflow/dags
      - ../pipeline:/opt/airflow/pipeline
      - ../requirements.txt:/requirements.txt 
      - ./keys:/opt/airflow/keys 
      - ../gx:/opt/airflow/gx         
      - ../data:/opt/airflow/data  
      - ../analysis:/opt/airflow/analysis
    ports:
      - "8080:8080"
    command: bash -c "pip install -r /requirements.txt && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.9.1-python3.9
    depends_on:
      - airflow-webserver
    env_file:
      - ../.env
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      PYTHONPATH: /opt/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "Etx684jFCwof8lADNZ8quOGEbG_eo6kh7HgFnKqbs8k"
    volumes:
      - ./dags:/opt/airflow/dags
      - ../pipeline:/opt/airflow/pipeline
      - ../requirements.txt:/requirements.txt 
      - ./keys:/opt/airflow/keys 
      - ../gx:/opt/airflow/gx
      - ../data:/opt/airflow/data 
      - ../analysis:/opt/airflow/analysis
    command: bash -c "pip install -r /requirements.txt && airflow scheduler"

  airflow-worker:
    image: apache/airflow:2.9.1-python3.9
    depends_on:
      - airflow-webserver
    env_file:
      - ../.env
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      PYTHONPATH: /opt/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "Etx684jFCwof8lADNZ8quOGEbG_eo6kh7HgFnKqbs8k"
    volumes:
      - ./dags:/opt/airflow/dags
      - ../pipeline:/opt/airflow/pipeline
      - ../requirements.txt:/requirements.txt 
      - ./keys:/opt/airflow/keys 
      - ../gx:/opt/airflow/gx
      - ../data:/opt/airflow/data 
      - ../analysis:/opt/airflow/analysis
    command: bash -c "pip install -r /requirements.txt && airflow celery worker"

volumes:
  postgres-db-volume: